# Generated by Django 2.1.13 on 2019-12-05 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScanSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(max_length=100, unique=True)),
                ('taskscan', models.CharField(max_length=150)),
                ('dtmodified', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
