# Generated by Django 2.1.13 on 2019-12-05 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanschedule',
            name='dtmodified',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
