# Generated by Django 2.1.13 on 2019-12-05 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secmgr', '0002_auto_20191205_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scanschedule',
            name='dtmodified',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
