# Generated by Django 2.1.13 on 2019-10-26 04:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programming', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgrammingFramework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('framework_name', models.CharField(max_length=40)),
                ('framework_type', models.CharField(max_length=40)),
                ('programming_authors', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programming.Programming_Authors')),
            ],
        ),
    ]
