# Generated by Django 3.0 on 2019-12-19 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socalert', '0002_auto_20191219_0823'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_alert',
            name='types',
            field=models.CharField(blank=True, choices=[('Net', 'Network/System'), ('Ser', 'Services'), ('Sec', 'Security')], max_length=50, null=True),
        ),
    ]
