# Generated by Django 2.1.15 on 2019-12-21 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socalert', '0003_event_alert_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_alert',
            name='contact',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
