# Generated by Django 3.0 on 2019-12-24 03:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socalert', '0006_event_alert_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event_alert',
            old_name='ackby',
            new_name='analyse_by',
        ),
    ]
