# Generated by Django 3.0 on 2019-12-24 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socalert', '0007_auto_20191224_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_alert',
            name='analyse_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
