# Generated by Django 3.0 on 2019-12-24 03:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socalert', '0008_event_alert_analyse_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_alert',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event_alert',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closedby2user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event_alert',
            name='is_closed',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event_alert',
            name='analyse_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst2user', to=settings.AUTH_USER_MODEL),
        ),
    ]
