# Generated by Django 2.1.15 on 2019-12-29 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socalert', '0010_event_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_rule',
            name='service',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
