# Generated by Django 2.1.15 on 2019-12-29 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socalert', '0011_event_rule_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='event_rule',
            name='types',
            field=models.CharField(blank=True, choices=[('Net', 'Network/System'), ('Ser', 'Services'), ('Sec', 'Security')], max_length=50, null=True),
        ),
    ]
